name: gauss
channels:
  - pytorch
  - nvidia
  - pyg
dependencies:
  - python=3.10
  - pip
  - click
  - pillow
  - scipy
  - pytorch==2.0.1
  - torchvision==0.15.2 
  - torchaudio==2.0.2
  - pytorch-cuda=11.8
  - tqdm
  - ninja
  - matplotlib
  - imageio
  - pyg
  - pytorch-scatter
  - pytorch-cluster
  - pip:
    - imgui
    - glfw
    - pyopengl
    - imageio-ffmpeg
    - pyspng
    - random-fourier-features-pytorch
    - wandb
    - git+https://github.com/graphdeco-inria/diff-gaussian-rasterization.git
