name: gaussgan
channels:
  - pytorch
  - nvidia
  - pyg
dependencies:
  - python=3.10
  - pip
  - pillow
  - scipy
  - tqdm
  - ninja
  - matplotlib
  - imageio
  # pytorch lightning
  - pytorch-lightning
  - torchmetrics[image]
  # pytorch
  - pytorch==2.0.1
  - torchvision==0.15.2 
  - pytorch-cuda=11.8
  # torch-geometric
  - pyg
  - pytorch-scatter
  - pytorch-cluster
  - pip:
    - ema-pytorch
    - imgui
    - glfw
    - pyopengl
    - imageio-ffmpeg
    - pyspng
    - random-fourier-features-pytorch
    - wandb
    - git+https://github.com/graphdeco-inria/diff-gaussian-rasterization.git