output_dir: outputs
device: cuda

train:
  ticks: 100
  batches_per_tick: 8
  save_images_every: 2

  discriminator_steps: 3
  weight_clip: 0.01

  loss:
    type: wgan
    noise_label: True
    gradient_penalty: True
    lambda_gp: 10

sphere:
  path: "spheres"
  points: 1024

dataset:
  type: synthetic
  params:
    path: datasets/cars_train.zip

dataloader:
  batch_size: 32
  num_workers: 1
  pin_memory: True

generator:
  model:
    k_neighbors: 20
    z_dim: 128

  optimizer:
    type: adamw
    params:
      lr: 0.002

discriminator:
  optimizer:
    type: sgd
    params:
      lr: 0.002